### PR TITLE
Fix/add to wish list

### PR DESCRIPTION
**Pull request by hectorfhurtado**
#### What?

Add Wishlist on Product pages functionality and basic styling

*Note* This depends on #83

### CODE REVIEW

**Comment by marcinkrzeminski** [comment]
@hectorfhurtado all good. Please merge this once you resolve things I pointed out in #83

**Comment by hectorfhurtado** [comment]
@marcinkrzeminski  I fixed the conflict but got the following message when trying to merge:

image

**Review by marcinkrzeminski — APPROVED** [review]

**Comment by marcinkrzeminski** [comment]
@hectorfhurtado I have approved that PR

**Comment by marcinkrzeminski** [comment]
@hectorfhurtado can we merge this?

**Pull request merged**
