### PR TITLE
Fix/write review

### PR DESCRIPTION
**Pull request by hectorfhurtado**
#### What?

Fix Wishlist functionality

*Note* this depends on #83

### CODE REVIEW

**Comment by marcinkrzeminski** [comment]
@hectorfhurtado looks good. Please merge once things from #83 are resolved

**Comment by hectorfhurtado** [comment]
@marcinkrzeminski I fixed the conflicts but I need your review in order to be able to merge. Please review. Thank you!

**Review by marcinkrzeminski — APPROVED** [review]

**Comment by marcinkrzeminski** [comment]
@hectorfhurtado approved. Please proceed with merge.

**Comment by marcinkrzeminski** [comment]
@hectorfhurtado can we merge this one as well?

**Pull request merged**
